site_name: VCCL Documentation
theme: 
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Version Information: version.md
  - Core Features:
    - Topology-Aware Load Balancing: features/topology-aware.md
    - PCIe Heterogeneity & Smart RNIC Selection: features/pcie-heterogeneity.md
    - Flow Telemetry: features/flow-telemetry.md
    - Fault Tolerance: features/fault-tolerance.md
    - SM Free & Overlap Training: features/sm-free-overlap.md
  - Usage Guide:
    - Download and Build: usage/installation.md
    - VCCL Tests: usage/nccl-tests.md
  - Environment Variables Reference: environment-variables.md